### ISSUE TITLE
Parsing certain terminal codes with xterm-color causes eshell to be slow

### ISSUE THREAD

**Issue by codesections** [atomontage/xterm-color#27] opened 2019-03-30 14:19 UTC
Thanks so much for this excellent package!  It really makes eshell very useable and generally works great!

However, I've encountered a strange issue where parsing certain strings with xterm-color will slow eshell to a crawl (e.g., after parsing the string, there will be a ~1 second lag between pressing a key and having that key show up on the screen).  Clearing eshell will resolve the problem.  Here is a minimal example of a string that triggers the issue:

```
[?1h=
[38;5;238m───────┬────────────────────────────────────────────────────────────────────────[0m[m
       [38;5;238m│ [0mFile: [1mtestfile[0m[m
[38;5;238m───────┼────────────────────────────────────────────────────────────────────────[0m[m
[38;5;238m   1[0m   [38;5;238m│[0m [38;5;231mhello world[0m[m
[38;5;238m───────┴────────────────────────────────────────────────────────────────────────[0m[m

[K[?1l>
```

(This string was generated using the excellent CLI app `bat`, which prints files with syntax highlighting.  Specifically, I ran `bat` over a file containing only the text `hello world`)

I've found a workaround for my particular use case (running `bat -n` avoids the issue).  But I wanted to mention it in case it is causing problems more broadly.

Please let me know if I can do anything else to help diagnose the problem.

**Comment by atomontage** [comment] 2019-03-30 15:50
I can't reproduce the issue here. If I just run bat testfile in eshell, then bat
refuses to use ANSI escapes. I assume it contains terminal detection code
which fails (as it should). I pretty much have to use "bat --color=always
testfile" and when I do that it works fine with no slowdown.

Are you running latest xterm-color.el?
Which version of Emacs/OS?
Did you byte compile xterm-color.el?

Screenshot attached.

**Comment by atomontage** [comment] 2019-03-30 15:52
![bat](https://user-images.githubusercontent.com/453886/55278401-382bec80-52e2-11e9-943c-e5df9ce29062.png)

**Comment by atomontage** [comment] 2019-03-30 16:41
Some more things for you to try:

In eshell do: setenv TERM eterm 
In M-x shell: export TERM=eterm

You should get perfect bat output with decorations after this (aligned lines),
since the DECSET/DECRST sequences will not be used by bat.

If you're still seeing a slowdown in eshell you might want to change
process-connection-type to nil. By default it's using a pty which is going
to cause a lot of problems in general. Here is the snippet from my own config:

```
;; Use pipes to communicate with spawned processes rather than TTYs
;; This solves a number of issues and makes things a lot faster to boot:
;;
;; + eshell pipes work without issue
;; + eshell runs a lot faster
;; + shell runs a lot faster but we lose job control

(setq process-connection-type nil)

;; shell advice so that it executes inside a let-binding that
;; sets process-connection-type to t since running shells without
;; ttys is not very useful.
(defun xristos/advice-shell (f &rest args)
  (let ((process-connection-type t))
    (apply f args)))

(advice-add 'shell :around #'xristos/advice-shell)

```

**Comment by codesections** [comment] 2019-03-31 14:28
Hmmm, none of those steps resolve the issue for me.  (If I add in the `process-connection-type` bit, I get the same result you mentioned: no color from `bat` unless I set `--color=always`.  But then I get the same slowdown when it prints the sidebar lines).

I'm happy to drop this/close the issue as Could Not Reproduce.  I prefer using `bat` without the lines anyway, so it won't impact me.  (And, it's easy enough to `clear` if it does come up.)  I'd only mentioned it in case it's more widespread but, based on your testing, it looks like it could just be a corner case with my config.

**Comment by atomontage** [comment] 2019-03-31 15:55
One final thing to try, copy paste the following into a new file, test.el:



(add-to-list 'load-path "path-to-xterm-color-dir")
(require 'xterm-color)

(require 'eshell)

(add-hook 'eshell-before-prompt-hook
          (lambda ()
            (setq xterm-color-preserve-properties t)))

(add-to-list 'eshell-preoutput-filter-functions 'xterm-color-filter)
(setq eshell-output-filter-functions (remove 'eshell-handle-ansi-color
eshell-output-filter-functions))



Now, start Emacs by running:

emacs -q -l test.el

This will skip your personal configuration.
Run M-x eshell and see if the issue happens again.

If it does, let me know what version of Emacs you're running and
what OS you're on.

If it doesn't, then something in your config is causing it.

**Comment by codesections** [comment] 2019-03-31 17:42
> If it doesn't, then something in your config is causing it.

Yep, something in my config is causing it.  I'll try selectively disabling lines in my config until I find the culprit and report back with what's causing the issue.  Thanks for the help running this down—definitely above and beyond!

**Comment by codesections** [comment] 2019-03-31 18:04
Hmm, I've identified the compatibility issue and it's kind of an unfortunate one: I encounter the issue whenever I'm using the smart-shell feature from [em-smart](https://github.com/emacs-mirror/emacs/blob/master/lisp/eshell/em-smart.el).  Specifically, I can use `bat` or other commands just fine if I *don't* run `eshell-smart-initialize`, but as so as I run `eshell-smart-initialize`, I start getting the same input lag I described above.

You've already helped out way more than I could have asked for, but I don't suppose you have any leads about where the incompatibility could be coming from, do you?

I consider the smart shell to be one of the killer features of eshell, so I'll probably stick to the workaround discussed up thread if I can't get the smart shell and xterm-color to play nicely together.  I'm guessing (without any basis) that other eshell users might also like the smart shell feature, so this issue might not be 100% idiosyncratic to my setup.

**Comment by atomontage** [comment] 2019-03-31 20:42
I still can't reproduce, with em-smart enabled.
Try this, in the previous test.el, after (require 'eshell)
add the following:

(require 'em-smart)
(add-hook 'eshell-mode-hook (lambda () (eshell-smart-initialize)))

Now run emacs again with emacs -q -l test.el, enter eshell and see
if it happens. If it doesn't then you need to narrow your config
down more.

I'm testing on Emacs 25, Emacs 26 and Emacs 27 and I don't see
what you describe.

**Comment by codesections** [comment] 2019-03-31 22:35
Thanks.  I dug into it a bit but wasn't able to figure out what in my config is causing the issue.  I'll keep looking, but probably won't be able to report back for a few days.  Thanks again for all your help!

**Comment by atomontage** [comment] 2019-04-01 01:16
I'm assuming the issue didn't happen with the updated test.el thus it's something else in your config that triggers it (possibly interacting with em-shell). I'm closing this as I can't reproduce but if you do manage to find the part of your config that triggers the issue, let me know and I'll have another look.

**Closed by atomontage** 2019-04-01 01:16 UTC

**Comment by codesections** [comment] 2019-04-01 02:14
I have identified the problem, and it was in one of the **last** places I would have expected problems with my config.  The problem comes from using certain fonts with both xterm-color and eshell.  Here is a minimum `test.el` config that reproduces the issue:

```elisp
(add-to-list 'load-path "~/.emacs.d/elpa/xterm-color-20190315.35")
(require 'xterm-color)

(require 'eshell)

(add-hook 'eshell-before-prompt-hook
          (lambda ()
            (setq xterm-color-preserve-properties t)))

(add-to-list 'eshell-preoutput-filter-functions 'xterm-color-filter)
(setq eshell-output-filter-functions
      (remove 'eshell-handle-ansi-color eshell-output-filter-functions))

(require 'em-smart)
(add-hook 'eshell-mode-hook (lambda () (eshell-smart-initialize)))
(add-to-list 'default-frame-alist
            '(font . "DejaVu Sans Mono-12"))

(setenv "PAGER" "")
(setenv "TERM" "eterm")
```

I showed the issue with `DejaVu Sans Mono`, since I know that to be a popular font for Emacs.  I was originally using `Hack`; the issue is the same for both fonts.  It does not occur with *all* fonts, however; the first font I found without the issue was `ubunu mono`.  I haven't yet figured out what the commonality for fonts causing the issue is.

This turned out to be one of the odder bugs I've encountered.  Thanks again for all your help!

(Oh, and this was on Emacs 26.1, since you'd asked about that earlier.)

**Comment by atomontage** [comment] 2019-04-01 02:39
This is bizarre, I still can't reproduce your issue.
I tried DejaVu Sans Mono and Hack without any problems.

Emacs 25, 26 and 27 compiled from git master.

The fact that it's triggered by a font?!? makes it extremely
likely that it's a bug in Emacs itself, possibly a bug in the
combination of Emacs/backend/display system.

**Comment by codesections** [comment] 2019-04-01 03:10
Totally agreed that it's bizarre!  But happy to leave this closed as `can't reproduce` and change fonts.  (I wasn't that tied to Hack anyway).

Thanks again for all your help.  I definitely owe you one
